# Generated by Django 4.2.4 on 2023-09-18 03:50

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=20, unique=True)),
                ("user_pw", models.CharField(max_length=64)),
            ],
        ),
    ]
