# Generated by Django 4.2.4 on 2023-09-18 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0003_alter_user_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="Memo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("memo_title", models.CharField(max_length=255, unique=True)),
                ("memo_text", models.TextField()),
            ],
        ),
    ]
