# Generated by Django 4.2.4 on 2023-09-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_app", "0004_memo"),
    ]

    operations = [
        migrations.AddField(
            model_name="memo",
            name="memo_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
